# A sample Gemfile
source "https://rubygems.org"

gem 'jekyll'
gem 'jekyll-assets'
gem 'github-pages', group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-picture-tag', '~> 0.2.3'
end



group :jekyll_plugins do
  gem 'jekyll-assets', github: 'jekyll/jekyll-assets'
  gem 'jekyll-sitemap', github: 'jekyll/jekyll-sitemap'
end